import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const contractPath = resolve(root, "contract.v1.json");
const contract = JSON.parse(await readFile(contractPath, "utf8"));
const canonical = JSON.stringify(sortValue(contract));
const contractHash = createHash("sha256").update(canonical).digest("hex");
const generated = {
  schema_version: contract.schema_version,
  contract_id: contract.contract_id,
  contract_hash: contractHash,
  resource_uri_version: contract.resource_uri_version,
  tools: contract.tools.map((tool) => ({
    ...tool,
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      openWorldHint: false,
      idempotentHint: tool.annotations?.idempotentHint ?? true
    },
    input_schema: {
      type: "object",
      additionalProperties: false,
      properties: tool.input,
      required: tool.required
    }
  })),
  reserved_write_tools: contract.reserved_write_tools
};
const ts = `// Generated by scripts/generate.mjs. Do not edit.\nexport const filmosToolContract = ${JSON.stringify(generated, null, 2)} as const;\nexport type FilmOSToolName = typeof filmosToolContract.tools[number]["name"];\n`;
const snapshot = `${JSON.stringify(generated, null, 2)}\n`;
const openapi = `${JSON.stringify({
  openapi: "3.1.0",
  info: { title: "FilmOS ChatGPT Tool Contract", version: contract.schema_version },
  paths: Object.fromEntries(generated.tools.map((tool) => [`/tools/${tool.name}`, {
    post: {
      operationId: tool.name,
      summary: tool.title,
      description: tool.description,
      "x-filmos-annotations": tool.annotations,
      "x-filmos-widget": tool.widget ?? null,
      requestBody: { required: true, content: { "application/json": { schema: tool.input_schema } } },
      responses: { "200": { description: "Read-only FilmOS tool result", content: { "application/json": { schema: { type: "object" } } } } }
    }
  }]))
}, null, 2)}\n`;

if (process.argv.includes("--check")) {
  const [actualTs, actualSnapshot, actualOpenApi] = await Promise.all([
    readFile(resolve(root, "src/generated.ts"), "utf8"),
    readFile(resolve(root, "generated/mcp-tools.v1.json"), "utf8"),
    readFile(resolve(root, "generated/openapi.v1.json"), "utf8")
  ]);
  if (actualTs !== ts || actualSnapshot !== snapshot || actualOpenApi !== openapi) {
    throw new Error("Tool Contract generated outputs are stale");
  }
} else {
  await Promise.all([
    writeFile(resolve(root, "src/generated.ts"), ts),
    writeFile(resolve(root, "generated/mcp-tools.v1.json"), snapshot),
    writeFile(resolve(root, "generated/openapi.v1.json"), openapi)
  ]);
}

function sortValue(value) {
  if (Array.isArray(value)) return value.map(sortValue);
  if (!value || typeof value !== "object") return value;
  return Object.fromEntries(Object.keys(value).sort().map((key) => [key, sortValue(value[key])]));
}
