import type { BrainCapabilities, BrainProfile } from "./contracts.js";

const nativeCapabilities: BrainCapabilities = {
    streamingChat: true,
    threadHistory: true,
    threadResume: true,
    imageInput: true,
    automaticVisualContext: true,
    mcpTools: true,
    read: true,
    preview: true,
    applyAfterHumanConfirmation: true,
    hostedProposalReturn: false,
    cancelTurn: true,
};

export const BUILTIN_BRAIN_PROFILES: readonly BrainProfile[] = [
    {
        id: "codex.subscription",
        displayName: "Codex",
        provider: "openai.codex",
        transport: "codex_app_server",
        authMode: "chatgpt_managed",
        billingMode: "subscription",
        interactionSurface: "native_stream",
        toolSurface: "workbench_operator",
        requiresApiKey: false,
        mayCreateSeparateCharges: false,
        availability: "enabled",
        capabilities: nativeCapabilities,
        legacy: { harness: "codex_app_server", billingMode: "subscription_quota", authMode: "chatgpt_account", interactionSurface: "embedded_chat" },
    },
    {
        id: "chatgpt.subscription.host",
        displayName: "ChatGPT",
        provider: "openai.chatgpt",
        transport: "chatgpt_host_mcp",
        authMode: "chatgpt_host",
        billingMode: "subscription",
        interactionSurface: "host_handoff",
        toolSurface: "chatgpt_hosted",
        requiresApiKey: false,
        mayCreateSeparateCharges: false,
        availability: "enabled",
        capabilities: {
            ...nativeCapabilities,
            streamingChat: false,
            threadHistory: true,
            threadResume: true,
            imageInput: false,
            automaticVisualContext: false,
            applyAfterHumanConfirmation: false,
            hostedProposalReturn: true,
            cancelTurn: false,
        },
        legacy: { harness: "chatgpt_hosted_app", billingMode: "external_host", authMode: "project_grant", interactionSurface: "hosted_chat" },
    },
    {
        id: "openai.api",
        displayName: "OpenAI GPT (API)",
        provider: "openai.gpt",
        transport: "model_api",
        authMode: "api_key",
        billingMode: "metered_api",
        interactionSurface: "native_stream",
        toolSurface: "workbench_operator",
        requiresApiKey: true,
        mayCreateSeparateCharges: true,
        availability: "disabled",
        capabilities: nativeCapabilities,
        legacy: { harness: "filmos_api_agent", billingMode: "metered_api", authMode: "api_key", interactionSurface: "embedded_chat" },
    },
    {
        id: "anthropic.api",
        displayName: "Claude (API)",
        provider: "anthropic.claude",
        transport: "model_api",
        authMode: "api_key",
        billingMode: "metered_api",
        interactionSurface: "native_stream",
        toolSurface: "workbench_operator",
        requiresApiKey: true,
        mayCreateSeparateCharges: true,
        availability: "disabled",
        capabilities: nativeCapabilities,
        legacy: { harness: "filmos_api_agent", billingMode: "metered_api", authMode: "api_key", interactionSurface: "embedded_chat" },
    },
    {
        id: "deepseek.api",
        displayName: "DeepSeek (API)",
        provider: "deepseek",
        transport: "model_api",
        authMode: "api_key",
        billingMode: "metered_api",
        interactionSurface: "native_stream",
        toolSurface: "workbench_operator",
        requiresApiKey: true,
        mayCreateSeparateCharges: true,
        availability: "disabled",
        capabilities: { ...nativeCapabilities, imageInput: false, automaticVisualContext: false },
        legacy: { harness: "filmos_api_agent", billingMode: "metered_api", authMode: "api_key", interactionSurface: "embedded_chat" },
    },
    {
        id: "local.model",
        displayName: "本地模型",
        provider: "local",
        transport: "local_model",
        authMode: "local",
        billingMode: "local_compute",
        interactionSurface: "native_stream",
        toolSurface: "workbench_operator",
        requiresApiKey: false,
        mayCreateSeparateCharges: false,
        availability: "disabled",
        capabilities: { ...nativeCapabilities, imageInput: false, automaticVisualContext: false },
        legacy: { harness: "openai_compatible_local", billingMode: "local_compute", authMode: "none", interactionSurface: "embedded_chat" },
    },
    {
        id: "human.only",
        displayName: "Human Only",
        provider: "human",
        transport: "human",
        authMode: "none",
        billingMode: "none",
        interactionSurface: "human",
        toolSurface: "runtime_admin",
        requiresApiKey: false,
        mayCreateSeparateCharges: false,
        availability: "enabled",
        capabilities: {
            streamingChat: false,
            threadHistory: true,
            threadResume: true,
            imageInput: false,
            automaticVisualContext: false,
            mcpTools: false,
            read: true,
            preview: true,
            applyAfterHumanConfirmation: true,
            hostedProposalReturn: false,
            cancelTurn: false,
        },
        legacy: { harness: "human_only", billingMode: "external_host", authMode: "none", interactionSurface: "hybrid_control" },
    },
] as const;

export function registerBuiltinBrainProfiles(registry: { registerProfile(profile: BrainProfile): unknown }, enabledProfileIds?: ReadonlySet<string>) {
    for (const profile of BUILTIN_BRAIN_PROFILES) registry.registerProfile(enabledProfileIds
        ? { ...profile, availability: enabledProfileIds.has(profile.id) ? "enabled" : "disabled" }
        : profile);
}
