import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const result = await build({
  entryPoints: [fileURLToPath(new URL("../src/widget-runtime.ts", import.meta.url))],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  write: false,
});
const source = result.outputFiles[0].text;
const output = new URL("../generated/widget-runtime.ts", import.meta.url);
await mkdir(new URL("../generated/", import.meta.url), { recursive: true });
await writeFile(output, `// Generated by scripts/build-widget.mjs. Do not commit.\nexport const WIDGET_RUNTIME_JS = ${JSON.stringify(source)};\n`);
