import { build } from "esbuild";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const result = await build({
  entryPoints: [fileURLToPath(new URL("../src/widget-runtime.ts", import.meta.url))],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  write: false,
});
const source = result.outputFiles[0].text;
await writeFile(new URL("../src/generated-widget-runtime.ts", import.meta.url), `// Generated by scripts/build-widget.mjs.\nexport const WIDGET_RUNTIME_JS = ${JSON.stringify(source)};\n`);
