import { z } from "zod";

const recordSchema = z.record(z.unknown());
const positionSchema = z.object({ x: z.number(), y: z.number() });
const viewportSchema = z.object({ x: z.number(), y: z.number(), k: z.number() });
const nodeTypeSchema = z.enum(["image", "text", "script", "video", "audio", "frame"]);
const generationModeSchema = z.enum(["text", "image", "video", "audio"]);
const projectIdSchema = z.string().min(1).optional();
const projectPromptTarget = { projectId: projectIdSchema, canvasId: z.string().min(1).optional(), nodeId: z.string().min(1), rowId: z.string().min(1), kind: z.enum(["image", "video"]) };
const projectCandidateSchema = z.object({ unitId: z.string().optional(), shotId: z.string().optional(), name: z.string().min(1), category: z.string().min(1), details: recordSchema.optional() });
const projectShotSchema = z.object({
    id: z.string().min(1).optional(), expectedRevision: z.number().int().min(0),
    title: z.string().min(1).max(240), description: z.string().min(1), position: z.number().int().min(0), durationMs: z.number().int().positive().max(3600000),
    content: z.object({
        sourceReferences: z.array(z.object({ paragraphId: z.string().min(1), quote: z.string().min(1) }).strict()).min(1).max(200),
        scene: z.string().min(1),
        characters: z.array(z.string().min(1)).max(100).describe("仅填写来源正文中逐字出现的角色名称，例如阿禾、索恩；不要把（仅屏幕影像）、画外音、身份或资产ID附加到姓名。出场方式、可见范围及动作保留在action/camera字段。"),
        dialogue: z.array(z.object({ speaker: z.string().min(1), text: z.string().min(1), paragraphId: z.string().min(1) }).strict()).max(200),
        action: z.string().min(1), camera: z.string().min(1),
    }).strict(),
}).strict();

export const toolNames = [
    "canvas_get_state",
    "canvas_get_context",
    "canvas_find_nodes",
    "canvas_get_node",
    "canvas_get_connection",
    "canvas_get_generation_tasks",
    "canvas_get_resources",
    "canvas_validate_ops",
    "canvas_get_selection",
    "canvas_export_snapshot",
    "canvas_apply_ops",
    "canvas_create_workflow",
    "canvas_create_node",
    "canvas_create_text_node",
    "canvas_create_text_nodes",
    "canvas_create_image_prompt_flow",
    "canvas_create_generation_flow",
    "canvas_generate_text",
    "canvas_generate_image",
    "canvas_generate_video",
    "canvas_generate_audio",
    "canvas_update_node",
    "canvas_update_node_text",
    "canvas_move_nodes",
    "canvas_resize_node",
    "canvas_delete_nodes",
    "canvas_connect_nodes",
    "canvas_select_nodes",
    "canvas_set_viewport",
    "canvas_run_generation",
    "project_get_context",
    "project_list_units",
    "project_get_script",
    "project_create_script",
    "project_get_script_batch",
    "project_get_script_revision",
    "project_revise_script",
    "project_extract_asset_candidates",
    "project_confirm_asset_candidate",
    "project_create_or_update_shots",
    "project_get_shots",
    "project_get_shot_batch",
    "project_get_shot_revisions",
    "project_sync_storyboard",
    "project_get_prompt",
    "project_read_shot_image",
    "project_save_prompt",
    "project_get_prompt_revision",
    "project_get_prompt_request",
    "project_link_shot_asset",
    "project_start_workflow_step",
    "project_link_asset",
    "project_upsert_asset_version",
    "project_register_task_output",
] as const;
export type ToolName = (typeof toolNames)[number];

export const canvasOpSchema = z.discriminatedUnion("type", [
    z.object({ type: z.literal("add_node"), nodeType: nodeTypeSchema.optional(), id: z.string().optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), position: positionSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("update_node"), id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("delete_node"), id: z.string().optional(), ids: z.array(z.string()).optional(), nodeType: nodeTypeSchema.optional() }).passthrough(),
    z.object({ type: z.literal("delete_connections"), id: z.string().optional(), ids: z.array(z.string()).optional(), all: z.boolean().optional() }).passthrough(),
    z.object({ type: z.literal("connect_nodes"), id: z.string().optional(), fromNodeId: z.string(), toNodeId: z.string(), fromHandleId: z.string().optional(), toHandleId: z.string().optional() }).passthrough(),
    z.object({ type: z.literal("set_viewport"), viewport: viewportSchema }).passthrough(),
    z.object({ type: z.literal("select_nodes"), ids: z.array(z.string()) }).passthrough(),
    z.object({ type: z.literal("run_generation"), nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }).passthrough(),
]);

const textNodeSchema = z.object({
    text: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    width: z.number().optional(),
    height: z.number().optional(),
});

const workflowNodeSchema = z.object({
    ref: z.string().min(1),
    kind: z.enum(["text", "script", "image", "video", "audio", "character_cards", "character_three_view", "storyboard_video"]),
    title: z.string().min(1),
    content: z.string().optional(),
    prompt: z.string().optional(),
    description: z.string().optional(),
    referenceRefs: z.array(z.string()).optional(),
    referenceNodeIds: z.array(z.string()).optional(),
    runGeneration: z.boolean().optional(),
    width: z.number().positive().optional(),
    height: z.number().positive().optional(),
});
const workflowSchema = z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    nodes: z.array(workflowNodeSchema).min(1),
    edges: z.array(z.object({ from: z.string().min(1), to: z.string().min(1) })).optional(),
    direction: z.enum(["horizontal", "vertical"]).optional(),
    start: positionSchema.optional(),
    gap: z.number().min(48).optional(),
    autoRun: z.boolean().optional(),
});

const generationOptionsSchema = z.object({
    model: z.string().optional(),
    size: z.string().optional(),
    quality: z.string().optional(),
    count: z.number().optional(),
    seconds: z.string().optional(),
    vquality: z.string().optional(),
    generateAudio: z.string().optional(),
    watermark: z.string().optional(),
    audioVoice: z.string().optional(),
    audioFormat: z.string().optional(),
    audioSpeed: z.string().optional(),
    audioInstructions: z.string().optional(),
});

const generationFlowSchema = z.object({
    prompt: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    referenceNodeIds: z.array(z.string()).optional(),
});

export const toolInputSchemas = {
    canvas_get_state: z.object({}).passthrough(),
    canvas_get_context: z.object({}).passthrough(),
    canvas_find_nodes: z.object({ query: z.string().optional(), ids: z.array(z.string()).optional(), types: z.array(z.string()).optional(), statuses: z.array(z.string()).optional(), resourceOnly: z.boolean().optional(), limit: z.number().int().min(1).max(200).optional() }),
    canvas_get_node: z.object({ id: z.string().min(1) }),
    canvas_get_connection: z.object({ id: z.string().min(1) }),
    canvas_get_generation_tasks: z.object({ status: z.string().optional(), nodeIds: z.array(z.string()).optional(), limit: z.number().int().min(1).max(200).optional() }),
    canvas_get_resources: z.object({ nodeIds: z.array(z.string()).optional(), status: z.string().optional(), limit: z.number().int().min(1).max(300).optional() }),
    canvas_validate_ops: z.object({ ops: z.array(canvasOpSchema) }),
    canvas_get_selection: z.object({}).passthrough(),
    canvas_export_snapshot: z.object({}).passthrough(),
    canvas_apply_ops: z.object({ ops: z.array(canvasOpSchema), expectedRevision: z.number().int().nonnegative().optional(), expectedStateHash: z.string().min(1).optional() }),
    canvas_create_workflow: workflowSchema,
    canvas_create_node: z.object({ nodeType: nodeTypeSchema, title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), metadata: recordSchema.optional() }),
    canvas_create_text_node: z.object({ text: z.string().optional(), x: z.number().optional(), y: z.number().optional(), title: z.string().optional(), width: z.number().optional(), height: z.number().optional() }),
    canvas_create_text_nodes: z.object({ items: z.array(textNodeSchema).min(1), x: z.number().optional(), y: z.number().optional(), gap: z.number().optional(), direction: z.enum(["row", "column"]).optional() }),
    canvas_create_image_prompt_flow: z.object({ prompt: z.string(), x: z.number().optional(), y: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_generation_flow: generationFlowSchema.extend({ mode: generationModeSchema.optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_generate_text: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_image: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_video: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_audio: generationFlowSchema.merge(generationOptionsSchema),
    canvas_update_node: z.object({ id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }),
    canvas_update_node_text: z.object({ id: z.string(), text: z.string(), title: z.string().optional() }),
    canvas_move_nodes: z.object({ items: z.array(z.object({ id: z.string(), x: z.number().optional(), y: z.number().optional(), dx: z.number().optional(), dy: z.number().optional() })).min(1) }),
    canvas_resize_node: z.object({ id: z.string(), width: z.number(), height: z.number(), freeResize: z.boolean().optional() }),
    canvas_delete_nodes: z.object({ ids: z.array(z.string()).min(1) }),
    canvas_connect_nodes: z.object({ connections: z.array(z.object({ fromNodeId: z.string(), toNodeId: z.string(), fromHandleId: z.string().optional(), toHandleId: z.string().optional() })).min(1) }),
    canvas_select_nodes: z.object({ ids: z.array(z.string()) }),
    canvas_set_viewport: z.object({ viewport: viewportSchema }),
    canvas_run_generation: z.object({ nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional(), retry: z.boolean().optional() }),
    project_get_context: z.object({ projectId: projectIdSchema }),
    project_get_script: z.object({ projectId: projectIdSchema, unitId: z.string().min(1) }),
    project_create_script: z.object({ projectId: projectIdSchema, expectedProjectRevision: z.number().int().positive(), requestId: z.string().min(1).max(100), note: z.string().min(1).max(1000), chapters: z.array(z.object({ title: z.string().min(1).max(240), sourceText: z.string().min(1).max(2 * 1024 * 1024) }).strict()).min(1).max(50) }),
    project_get_script_batch: z.object({ projectId: projectIdSchema, requestId: z.string().min(1).max(100) }),
    project_get_prompt: z.object(projectPromptTarget).strict(),
    project_read_shot_image: z.object({ projectId: projectIdSchema, canvasId: z.string().min(1).optional(), nodeId: z.string().min(1), rowId: z.string().startsWith("project-shot:"), expectedImageHash: z.string().regex(/^[a-f0-9]{64}$/).optional() }).strict(),
    project_save_prompt: z.object({ ...projectPromptTarget, requestId: z.string().min(1).max(100), expectedRevision: z.number().int().min(0), expectedContentHash: z.string().regex(/^[0-9a-f]{64}$/), dependencyHash: z.string().regex(/^[0-9a-f]{64}$/), prompt: z.string().min(1).max(65536) }).strict(),
    project_get_prompt_revision: z.object({ ...projectPromptTarget, revision: z.number().int().min(0) }).strict(),
    project_get_prompt_request: z.object({ ...projectPromptTarget, requestId: z.string().min(1).max(100) }).strict(),
    project_get_script_revision: z.object({ projectId: projectIdSchema, unitId: z.string().min(1), revision: z.number().int().positive() }),
    project_revise_script: z.object({ projectId: projectIdSchema, unitId: z.string().min(1), expectedRevision: z.number().int().positive(), requestId: z.string().min(1).max(100), note: z.string().min(1).max(1000), edits: z.array(z.object({ oldText: z.string().min(1).max(2 * 1024 * 1024), newText: z.string().max(2 * 1024 * 1024) }).strict()).min(1).max(20) }),
    project_list_units: z.object({ projectId: projectIdSchema, kind: z.string().optional(), status: z.string().optional() }),
    project_extract_asset_candidates: z.object({ projectId: projectIdSchema, candidates: z.array(projectCandidateSchema).min(1).max(100) }),
    project_confirm_asset_candidate: z.object({ projectId: projectIdSchema, candidateId: z.string().min(1), assetId: z.string().optional() }),
    project_get_shots: z.object({ projectId: projectIdSchema, unitId: z.string().min(1) }),
    project_sync_storyboard: z.object({ projectId: projectIdSchema, unitId: z.string().min(1), expectedShotRevision: z.number().int().min(0), sourceRevision: z.number().int().positive(), sourceHash: z.string().regex(/^[0-9a-f]{64}$/) }).strict(),
    project_get_shot_batch: z.object({ projectId: projectIdSchema, unitId: z.string().min(1), requestId: z.string().min(1).max(100) }),
    project_get_shot_revisions: z.object({ projectId: projectIdSchema, shotId: z.string().min(1) }),
    project_create_or_update_shots: z.object({ projectId: projectIdSchema, unitId: z.string().min(1), requestId: z.string().min(1).max(100), expectedShotRevision: z.number().int().min(0), sourceRevision: z.number().int().positive(), sourceHash: z.string().regex(/^[0-9a-f]{64}$/), sourceParagraphIds: z.array(z.string().min(1)).min(1).max(20000), shots: z.array(projectShotSchema).min(1).max(100) }).strict(),
    project_link_shot_asset: z.object({ projectId: projectIdSchema, shotId: z.string().min(1), assetVersionId: z.string().min(1), role: z.enum(["reference", "start_frame", "end_frame", "keyframe", "storyboard", "output"]) }),
    project_start_workflow_step: z.object({ projectId: projectIdSchema, stepId: z.string().min(1) }),
    project_link_asset: z.object({ projectId: projectIdSchema, assetId: z.string().min(1), category: z.string().min(1) }),
    project_upsert_asset_version: z.object({ projectId: projectIdSchema, assetId: z.string().min(1), prompt: z.string().optional(), definitionJson: z.string().optional(), note: z.string().optional() }),
    project_register_task_output: z.object({ projectId: projectIdSchema, stepId: z.string().min(1), taskId: z.string().min(1), assetVersionId: z.string().optional(), resourceId: z.string().optional(), mediaType: z.string().optional(), role: z.enum(["reference", "start_frame", "end_frame", "keyframe", "storyboard", "output"]).optional(), metadataJson: z.string().optional(), outputJson: z.string().optional() }),
} satisfies Record<ToolName, z.AnyZodObject>;

export const toolDescriptions: Record<ToolName, string> = {
    project_read_shot_image: "读取当前授权画布指定业务镜头的已保存图片，返回真实MCP图片内容及图片SHA256、资源版本、镜头/完整剧本和场景约束。先读工作台/分镜取得真实script nodeId、project-shot:镜头ID rowId，不猜ID、不接受文件路径或URL；需要复核同一原图时携带expectedImageHash。缺图、旧来源、错项目、读取期间手改、过期或无法解码会明确失败；没有image内容不得声称看见。binding只证明当前行引用，不证明图片生成时的来源。反馈须分开观察事实、引用约束、判断、置信度/未知和建议，并标明本次binding及图像哈希；看不清应说明，审美偏好不是客观违规。此工具不保存诊断/修改图片、不生成、不做QC批准。",
    canvas_get_state: "读取当前网页画布的节点、连线、选区和视口。",
    canvas_get_context: "读取面向 Agent 的语义化画布上下文：节点用途、连接关系、选区、资源引用、生成状态和状态哈希。优先于直接猜测节点 metadata。",
    canvas_find_nodes: "按标题、内容、提示词、类型、状态、资产或工作流检索真实节点，返回可用于后续写操作的节点 id。",
    canvas_get_node: "按真实节点 id 精确读取单个节点的语义、完整安全 metadata、资源状态和关联连线；找不到时明确返回未找到。",
    canvas_get_connection: "按真实连线 id 精确读取连线端点、端点节点摘要和 handle 信息；找不到时明确返回未找到。",
    canvas_get_generation_tasks: "读取当前画布节点已经绑定的生成任务观察状态，包括 taskId、节点、任务状态、进度、阶段和错误；这是画布快照观察，不会主动轮询上游。",
    canvas_get_resources: "读取当前画布引用的媒体资源清单，包括资源/资产引用、类型、尺寸、大小、时长和就绪状态；不会返回媒体 URL。",
    canvas_validate_ops: "在真正写入前校验批量操作中的节点 id、连接关系和参数，避免对不存在节点或错误资源执行操作。",
    canvas_get_selection: "读取当前网页画布选中的节点。",
    canvas_export_snapshot: "导出当前画布快照，用于理解布局。",
    canvas_apply_ops: "批量操作当前网页画布。ops 支持 add_node、update_node、delete_node、delete_connections、connect_nodes、set_viewport、select_nodes、run_generation。",
    canvas_create_workflow: "创建语义化工作流/流水线。character_cards 是角色拆分图片卡片，character_three_view 是角色三视图，storyboard_video 是分镜剧情视频。媒体节点必须有 prompt/content；已有素材使用先读取到的真实 node id 填入 referenceNodeIds。自动分配 id、根据真实节点尺寸布局、建立 edges/referenceRefs/referenceNodeIds 连线并返回可验证结果；不要用批量文本节点代替工作流。",
    canvas_create_node: "创建任意类型节点：text、script、image、video、audio、frame。适合创建脚本、媒体占位、背板或自定义 metadata 节点。",
    canvas_create_text_node: "在当前画布创建单个文本节点。",
    canvas_create_text_nodes: "批量创建文本节点，适合生成标题、段落、脚本、说明等内容块。",
    canvas_create_image_prompt_flow: "创建提示词文本节点和图片目标节点并自动连线，可选择立即触发生图。",
    canvas_create_generation_flow: "创建通用生成流程：提示词文本节点、对应类型的生成目标节点和参考节点连线，可用于文案、生图、视频或音频。",
    canvas_generate_text: "创建通用文本生成流程并立即触发生成。",
    canvas_generate_image: "创建通用图片生成流程并立即触发生成。",
    canvas_generate_video: "创建通用视频生成流程并立即触发生成。",
    canvas_generate_audio: "创建通用音频生成流程并立即触发生成。",
    canvas_update_node: "更新节点基础字段或 metadata。",
    canvas_update_node_text: "更新文本节点内容和标题。",
    canvas_move_nodes: "移动一个或多个节点，支持绝对坐标或 dx/dy 偏移。",
    canvas_resize_node: "调整节点尺寸。",
    canvas_delete_nodes: "删除指定节点及相关连线。",
    canvas_connect_nodes: "批量连接节点。",
    canvas_select_nodes: "设置当前选中节点。",
    canvas_set_viewport: "调整画布视口。",
    canvas_run_generation: "触发指定节点生成；对已有生成任务明确重试时传 retry=true，以复用产品级重试幂等身份。",
    project_get_context: "读取当前短剧项目的章节、画布、资产、镜头、候选和工作流事实。",
    project_get_script: "读取当前项目一个章节的真实完整正文、修订号和哈希。修改剧本前必须读取，不能从章节摘要或画布节点标题推测正文。",
    project_create_script: "将已创作的1–50个完整章节追加到当前授权项目，不是调用模型API。先project_get_context读取project.revision作为expectedProjectRevision；使用稳定requestId及创作说明note。正文sourceText使用工作台HTML段落格式，保留完整对白/场景/动作。整批原子保存v1历史并回读，不覆盖已有章节，不生成素材。丢回执先project_get_script_batch，确认同一请求后方可原参数重试，不能换ID重复建章。保存后打磨用project_get_script及project_revise_script，保留v1；verification.matchesCurrent=false时已有后续修改，须读最新正文。",
    project_get_script_batch: "按原requestId回读建章批次及v1正文/哈希，比较当前章节是否仍匹配。只读恢复，不续建、不调用模型；旧初稿回执不是最新正文。",
    project_get_prompt: "读取当前授权画布的业务分镜行图片/视频提示词、state、真实项目/脚本修订/镜头/素材版本依赖、dependencyHash、过期标志和历史目录。先用canvas_get_context或canvas_get_node获取真实script nodeId和rowId；rowId为project-shot:业务镜头ID，禁止猜造。kind=image为静态首帧草稿，video为视频运动草稿。dependencies.guidance复用原生模板及用户定制，与全文来源一起作为编写依据；它不是已保存提示词，不代表模型参数已适配。素材/模板/用户定制变化会使旧稿过期。保存前必须读本工具；writeBlockers非空先修来源/同步分镜。localOverrides是画布手工调整，不擅自覆盖。素材元数据不代表看见像素。",
    project_save_prompt: "将创作提示词逐字保存到当前画布业务分镜行并回读当前、历史和原请求；不生成、不上传、不正式批准。与普通原生编辑器共用保存路径。先project_get_prompt，用读取的state.revision/state.contentHash和当前dependencyHash；requestId稳定、同一请求重试不换ID。prompt只含对应镜头草稿，保留真实人物/动作/道具/空间和风格；无明确生成模型时是创作草稿，不冒充模型参数适配。版本冲突回读当前再核对，未知结果先project_get_prompt_request。verification不全通过不能报告当前完成。",
    project_get_prompt_revision: "精确回读提示词历史版本；revision=0是首次纳管前原稿，可能没有来源证据，不能用当前素材补写旧版。历史只读，不自动恢复或生成。",
    project_get_prompt_request: "按原requestId回读提示词保存回执，校验当前授权画布与目标行；用于丢响应/中断恢复。历史回执不是当前版本，继续编辑前project_get_prompt，禁止换requestId盲重写。",
    project_get_script_revision: "回读指定章节修订的真实正文与哈希；用于原版、新版比较和保存后的核验。不会修改或锁定剧本。",
    project_revise_script: "按已读取正文中的唯一 oldText 片段进行精确替换，未指定的正文保持不变。沿用 sourceFormat，保留 HTML 格式；使用读取到的 expectedRevision，每次逻辑修订一个 requestId，重试复用相同 ID 和参数。保存修订历史并回读验证，失败不得报完成。不修改已完成章节、不批准或锁定 Film Core 剧本，也不生成素材。",
    project_list_units: "按类型或状态筛选当前短剧项目的章节/项目单元。",
    project_extract_asset_candidates: "将分镜识别出的角色、场景、服饰、道具或武器需求登记为待确认资产候选。",
    project_confirm_asset_candidate: "确认一个资产候选，创建正式资产或关联已有个人资产。",
    project_get_shots: "读取指定章节完整脚本、段落ID/原文和识别出的精确dialogue、脚本revision/sourceHash、shotRevision、当前业务镜头、来源覆盖和过期ID。拆镜前必须读全文，不能凭摘要。段落ID只在该章该版本有效；coverage.chapterComplete只证明来源引用和标识对白覆盖，不证明空间/导演质量。",
    project_sync_storyboard: "将已保存且来源未过期的业务分镜同步到当前授权画布，复用原生分镜导入；不新建画布、不生成、不上传。先project_get_shots，以unit.shotRevision、unit.revision、sourceHash作为expectedShotRevision、sourceRevision、sourceHash。保留既有节点/行ID、手写提示词、素材、布局及连接；手工改动或版本冲突拒绝覆盖，不用canvas_apply_ops重建绕过。成功返回真实nodeId、rowId和shotId供project_get_prompt接续。verification必须全部通过才能继续依赖该映射；persisted=true但ok=false表示需要回读核对，不代表可以重建对象。",
    project_get_shot_batch: "用原requestId回读已持久化的镜头批次，供响应丢失/重试恢复。历史回执不是最新镜头；继续编辑前用project_get_shots回读当前状态。",
    project_get_shot_revisions: "读取指定真实业务镜头的追加修订历史；保留原ID、对白、来源及内容，不修改任何数据。",
    project_create_or_update_shots: "按真实脚本制作或局部修订业务分镜，整批原子保存并回读；不生图、不批准。先project_get_shots，sourceParagraphIds明确本次范围，全章任务包含全部段落，局部修改须保留目标镜头原有来源。引用合起来覆盖范围全文；使用返回paragraph.dialogue的speaker/text（含空格），不可遗漏、重复、改说话人或颠倒顺序，长句可分配到连续镜头但拼接必须逐字等于原文。带原sourceRevision/sourceHash和unit.shotRevision；新镜头不传id且expectedRevision=0，更新用原id/revision，只传需保存项，其余镜头/引用不删。导演以场景节拍为单位，不机械逐句切镜或预设镜数；content.camera交代镜头任务/触发、景别、机位方向/轴线、运动或固定、可见人物/背景、变镜理由；content.action交代动作归属、道具起止状态、目光/听者反应和结束状态；时长留足对白、呼吸与反应，不为平台时限强拆。人物和空间未确定时如实注明，不发明事实。稳定requestId，网络失败先回读原批次；勿换ID盲建。matchesCurrent=false或coverage.chapterComplete=false不可称全章已完成。",
    project_link_shot_asset: "将具体资产版本按首帧、尾帧或参考等用途关联到镜头。",
    project_start_workflow_step: "启动项目或章节制作流程中的一个步骤。",
    project_link_asset: "将个人资产引用到当前短剧项目，不复制媒体文件。",
    project_upsert_asset_version: "为项目资产创建新的设定和提示词版本，保留历史版本。",
    project_register_task_output: "将成功生成任务挂到流程步骤，并登记到具体资产版本和资源表示。",
};
